# Site
repository: ganesh47/aboutme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ganesh Raman
title: Senior Manager, Data Platforms
email: raman.ganesh@outlook.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ganesh47
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ganesh-raman-1a0b53229
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, am Ganesh. Currently, serve Senior Manager, Data Platforms, at HBK - Hottinger Brüel & Kjær.Working across people and technologies, have fun leading and manaing teams while helping build great analytics products in a niche domain. 

  Having grown as a Principal Engineer, have lot of depth, building data-platforms, cloud-PaaS-Platforms powering SaaS products across industries.This depth of knowledge helps build lasting relationships across a spectrum of people and technologies, empowering  

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Senior Manager, Data Platforms at HBK - Hottinger Brüel & Kjær
        link: www.hbkworld.com/en
        link_text: Hottinger Brüel & Kjær
        sub_title: Senior Manager, Data Platforms
        caption: September 2021 - Present (Through VIMANA acquisition)
        quote: >
          Enabling data platform teams towards building great analytics products
        description: | # this will include new lines to allow paragraphs
            Serving as the "Head of Data Platforms" in HBK, enable data-platform teams build great products across value-streams and the organisation. Role involved both people-management and leadership towards delivering great products.Enabling healthy teams, ensuring psycological safety across levels within teams as well with cross-organisational interactions.
      - layout: left
        title: Principal Engineer at VIMANA
        link: govimana.com
        link_text: VIMANA
        sub_title: Principal Engineer
        caption: December 2017 - September 2021 (Got acquired into HBK - Hottinger Brüel & Kjær)
        quote: >
          Enabling VIMANA's SaaS and PaaS products towards Smart Manufacturing
        description: | # this will include new lines to allow paragraphs
            Served as a "Principal Engineer" in VIMANA, across teams, leading product capabilities, across both SaaS and PaaS lines. Role involved solving complex technical problems, across data engineering, IoT, cloud, PaaS, SaaS and working within Smart-Manufacturing as a domain. Role also involve small degree of people managment towards building high-performance teams.
      - layout: left
        title: Senior Data Engineer at The Data Team
        link: thedatateam.com
        link_text: The Data Team
        sub_title: Senior Data Engineer
        caption: October 2015 - December 2017
        quote: >
          Solving complex data challenges across enterprises, small and big, building Data Platforms and Products 
        description: | # this will include new lines to allow paragraphs
            Served as a "Senior Data Engineer" in The Data Team.Was amongst the earliest of employees, joing while 'The Data Team' was a Data Strategy Consulting startup, working with large and small enterprises.Was pivotal in hiring, building teams, from ground-up, while also serving customer needs for Data Products.Helped build peta-byte-scale data-lake, for a global Banking customer, from Architechture to Execution, while collaborating across the length and bredth of the Enterprise 
      - layout: left
        title: Developer at Zafin
        link: zafin.com
        link_text: Zafin
        sub_title: Developer, R&D
        caption: May 2012 - October 2015
        quote: >
          Building Pricing and Billing products for Banks
        description: | # this will include new lines to allow paragraphs
            Worked with Core R&D team, solving complex technology challenges in building customer facing as well as back-end products, in the domain of "Pricing & Billing" for Banks. Experienced a range of polyglot technologies, right from building DSL platforms, to JVM Performance engineering for high-throughput processing with RDBMs, to building web front-end applications and RCP applications with GWT and Eclipse's RCP technolgies. Worked under great mentors and leaders, in both remote as well office settings.
      - layout: left
        title: Graduate Engineering Trainee at Standard Chartered Bank GBS
        link: www.sc.com/in/about-us/
        link_text: Standard Chartered Bank GBS
        sub_title: Graduate Engineering Trainee, eBBS-Core Banking
        caption: Feb 2011 - May 2012
        quote: >
          Developer within eBBS Core Banking Team
        description: | # this will include new lines to allow paragraphs
            Worked with Core Banking eBBS team, as part of multiple initiatives and was the recipient of multiple awards, including "Tech Wizard Sustainability Champion of 2011".

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NIT Kurukshetra
        caption: 2006 - 2010
        sub_title: B.Tech in Information Technology
        quote: >
          Established in 1963, as Regional Engineering College, Kurukshetra is known for Engineering as well as global alumuni.
        description: | # this will include new lines to allow paragraphs
          Majored in IT while specialising in Distributed Systems, while working on a paper around "Byzantine Fault Tolerance"
          

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
