# Site
repository: ganesh47/aboutme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ganesh Raman
title: Head of Software Platforms, HBK
email: raman.ganesh@outlook.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  ganesh47
linkedin_username: ganesh-raman-1a0b53229


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, am Ganesh, presently Heading Software Platforms, at HBK - Hottinger Brüel & Kjær.
  
  Love building, transforming products, learning, growing, scaling fun teams.
  Hands-on with technology, helps me create great product experiences building fun and sustainable ecosystems around people and products
  Having grown as a Principal Engineer, depth of  building platforms, products, teams, has been influential in building lasting relationships across a spectrum of people and technologies.  

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Head of Software Platforms
        link: www.hbkworld.com/en
        link_text: Hottinger Brüel & Kjær
        sub_title: Hottinger Brüel & Kjær
        caption: September 2021 - Present (Through VIMANA acquisition)
        quote: >
          Enabling data platform teams towards building great analytics products
        description: | # this will include new lines to allow paragraphs
            Heading Software Platforms at HBK, as a Digital-leader, influencing products, portfolios and business within HBK.
            Also head the-platform-team, learning, growing, building, scaling and sustaining healthy, high-performance teams in a fully-distributed, remote settings.
            Drive and execute Digital software stragegy as part of the Digital leadership within HBK.
            Drive tehnology leadership as part of tech-leadership-groups within HBK.
            Fully Remote.
      - layout: left
        title: Principal Engineer
        link: govimana.com
        link_text: VIMANA
        sub_title: VIMANA
        caption: December 2017 - September 2021 (Got acqui-hired into HBK - Hottinger Brüel & Kjær)
        quote: >
          Enabling VIMANA's SaaS and PaaS products towards Smart Manufacturing
        description: | # this will include new lines to allow paragraphs
            Served as a "Principal Engineer" in VIMANA, across teams, leading product capabilities, across both SaaS and PaaS product-lines.  
            Role involved solving complex technical problems, across data engineering, IoT, cloud, PaaS, SaaS and working within Smart-Manufacturing as a domain.
            Role also involve small degree of people managment towards building high-performance teams.
            Hybrid settings involving both remote and some in-office
      - layout: left
        title: Senior Data Engineer
        link: thedatateam.com
        link_text: The Data Team
        sub_title: The Data Team
        caption: October 2015 - December 2017
        quote: >
          Solving complex data challenges across enterprises, small and big, building Data Platforms and Products 
        description: | # this will include new lines to allow paragraphs
             As a "Senior Data Engineer" in The Data Team, was amongst the earliest of employees, joing while 'The Data Team' was a Data Strategy Consulting startup.
             
             Was pivotal in building teams, from ground-up, while also serving customer needs for Data Products.
             Helped build peta-byte-scale data-lake, for a global Banking customer, from Architechture to Execution, while collaborating across the length and breath of the enterprise.
             
             Hybrid settings involving both remote and some in-office 
      - layout: left
        title: Developer, R&D
        link: zafin.com
        link_text: Zafin
        sub_title: Zafin
        caption: May 2012 - October 2015
        quote: >
          Building Pricing and Billing products for Banks
        description: | # this will include new lines to allow paragraphs
            Worked with Core R&D team, solving complex technology challenges in building customer facing as well as back-end products.
            
            Experienced a range of polyglot technologies, right from building DSL platforms, to JVM Performance engineering for high-throughput processing with RDBMs, to building web front-end applications and RCP applications with GWT and Eclipse's RCP technolgies. 
            
            Worked under great mentors and leaders, in both remote as well office settings.
            
            Hybrid settings involving both remote and some in-office
      - layout: left
        title: Graduate Engineering Trainee, eBBS-Core Banking
        link: www.sc.com/in/about-us/
        link_text: Standard Chartered Bank GBS
        sub_title: Standard Chartered Bank GBS
        caption: Feb 2011 - May 2012
        quote: >
          Developer within eBBS Core Banking Team
        description: | # this will include new lines to allow paragraphs
            Worked with Core Banking eBBS team, as part of multiple initiatives and was the recipient of multiple awards, including "Tech Wizard Sustainability Champion of 2011".
            
            Fully In-Office.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NIT Kurukshetra
        caption: 2006 - 2010
        sub_title: B.Tech in Information Technology
        quote: >
          Established in 1963, as Regional Engineering College, Kurukshetra is known for Engineering as well as global alumuni.
        description: | # this will include new lines to allow paragraphs
          Majored in IT while specialising in Distributed Systems, while working on a paper around "Byzantine Fault Tolerance"
          

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
